###############################################################################
# © Copyright IBM Corporation 2020, 2026
###############################################################################

###############################################################################
# Requirements:
#     - IBM z/OS core collection 2.0.0 or later
###############################################################################

- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:
    - name: Remove user from z/OS system
      include_role:
        name: remove-zos-user
