# Copyright (c) IBM Corporation 2025
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
name: generate_data_set_name
author: Marcel Gutierrez (@AndreMarcel99)
version_added: "2.0.0"
short_description: Filter HLQs to generate a new random valid data set name.
description:
    - Provide a valid temporary data set name.
options:
    value:
      description:
        - High level qualifier to be used in the data set names.
      type: str
      required: true
      samples: USER
    middle_level_qualifier:
      description:
        - Middle level qualifier to be used in the data set names.
      type: str
      required: false
    low_level_qualifier:
      description:
        - Low level qualifier to be used in the data set names.
      type: str
      required: false
    num_names:
      description:
        - Number of data set names to be generated.
      type: int
      required: false
'''

EXAMPLES = r'''
- name: Filter to get one data set name
  set_fact:
    data_set_name: "{{ hlq | ibm.ibm_zos_core.generate_data_set_name }}"

- name: Filter to get a data set name with a specific middle level qualifier
  set_fact:
    data_set_name: "{{ hlq | ibm.ibm_zos_core.generate_data_set_name(middle_level_qualifier='MLQADM') }}"

- name: Filter to generate a data set name with a specific low level qualifier
  set_fact:
    data_set_name: "{{ hlq | ibm.ibm_zos_core.generate_data_set_name(low_level_qualifier='LLQADM') }}"

- name: Filter to generate a data set name with a specific middle and low level qualifier
  set_fact:
    data_set_name: "{{ hlq | ibm.ibm_zos_core.generate_data_set_name(middle_level_qualifier='MLQADM', low_level_qualifier='LLQADM') }}"

- name: Filter to generate 10 data set names
  set_fact:
    data_set_names: "{{ hlq | ibm.ibm_zos_core.generate_data_set_name(num_names=10) }}"

- name: Filter to generate 3 data set names with a specific low level qualifier
  set_fact:
    data_set_names: "{{ hlq | ibm.ibm_zos_core.generate_data_set_name(low_level_qualifier='LLQADM', num_names=3) }}"

- name: Filter to generate 5 data set names with a specific middle level qualifier
  set_fact:
    data_set_names: "{{ hlq | ibm.ibm_zos_core.generate_data_set_name(middle_level_qualifier='MLQADM', num_names=5) }}"
'''

RETURN = r'''
  _value:
    description: Name or names generated by the filter.
    type: list
    elements: str
'''


import secrets
import string
import re
from ansible.errors import AnsibleFilterError


def generate_data_set_name(value, middle_level_qualifier="", low_level_qualifier="", num_names=1):
    """Filter to generate valid data set names

    Args:
        value {str} -- value of high level qualifier to use on data set names
        middle_level_qualifier {str,optional} --  str of a possible qualifier
        low_level_qualifier {str, optional} -- str of a possible qualifier
        num_names {int, optional} -- number of dataset names to generate. Defaults to 1.

    Returns:
        list -- the total dataset names valid
    """
    if value is None or value == "":
        raise AnsibleFilterError("A High-Level Qualifier is required.")

    hlq = validate_qualifier(qualifier=value)
    mlq = ""
    llq = ""

    if bool(middle_level_qualifier):
        mlq = validate_qualifier(qualifier=middle_level_qualifier)

    if bool(low_level_qualifier):
        llq = validate_qualifier(qualifier=low_level_qualifier)

    if num_names > 1:
        dataset_names = []
        for generation in range(num_names):
            name = hlq + get_tmp_ds_name(middle_level_qualifier=mlq, low_level_qualifier=llq)
            dataset_names.append(name)
    else:
        dataset_names = hlq + get_tmp_ds_name(middle_level_qualifier=mlq, low_level_qualifier=llq)

    return dataset_names


def get_tmp_ds_name(middle_level_qualifier="", low_level_qualifier=""):
    """Unify the random qualifiers generated into one name.

    Args:
        middle_level_qualifier {str,optional} -- valid str of a qualifier
        low_level_qualifier {str, optional} -- valid str of a qualifier

    Returns:
        str: valid data set name
    """
    ds = "."

    if bool(middle_level_qualifier):
        ds += middle_level_qualifier + "."
    else:
        ds += "P" + get_random_q() + "."

    ds += "C" + get_random_q() + "."

    if bool(low_level_qualifier):
        ds += low_level_qualifier
    else:
        ds += "T" + get_random_q()

    return ds


def get_random_q():
    """Function or test to ensure random hlq of datasets"""
    # Generate the first random hlq of size pass as parameter
    letters = string.ascii_uppercase + string.digits
    random_q = ''.join(secrets.choice(letters)for iteration in range(7))
    count = 0
    # Generate a random HLQ and verify if is valid, if not, repeat the process
    while count < 5 and not re.fullmatch(
        r"^(?:[A-Z$#@]{1}[A-Z0-9$#@-]{0,7})",
        random_q,
        re.IGNORECASE,
    ):
        random_q = ''.join(secrets.choice(letters)for iteration in range(7))
        count += 1
    return random_q


def validate_qualifier(qualifier):
    """Function to validate a qualifier with naming rules.

    Args:
        qualifier (str): Str to validate as a Qualifier.

    Raises:
        AnsibleFilterError: Error of the valid len on the qualifier.
        AnsibleFilterError: Error on naming convention on the qualifier.

    Returns:
        str: Valid qualifier in upper case.
    """
    qualifier = qualifier.upper()

    if len(qualifier) > 8:
        raise AnsibleFilterError(f"The qualifier {qualifier} is too long for the data set name.")

    pattern = r'^[A-Z@#$][A-Z0-9@#$]{0,7}$'
    if bool(re.fullmatch(pattern, qualifier)):
        return qualifier
    else:
        raise AnsibleFilterError(f"The qualifier {qualifier} is not following the rules for naming conventions.")


class FilterModule(object):
    """ Jinja2 filter for the returned list or string by the collection module. """
    def filters(self):
        return {
            'generate_data_set_name': generate_data_set_name
        }
