---
- name: Update {{worker_type | default('worker')}} node label
  block:
    - name: Apply {{worker_type | default('worker')}} node label
      environment:
        KUBECONFIG: "./auth/kubeconfig"
      ansible.builtin.shell: |
        ./kubectl label node {{workerid}} node-role.kubernetes.io/{{worker_type | default('worker')}}='' --kubeconfig auth/kubeconfig &> /dev/null
        echo $(./oc get nodes -o custom-columns=NAME:.metadata.name)
      register: result
      until: result.stdout.find(workerid) != -1
      retries: 30
      delay: 10
  rescue:
    - name: Update {{worker_type | default('worker')}} node label manually
      ansible.builtin.debug:
        msg: "Please update {{worker_type | default('worker')}} node label manually via: ./kubectl label node {{workerid}} node-role.kubernetes.io/{{worker_type | default('worker')}}='' --kubeconfig auth/kubeconfig"

- name: Update the {{worker_type | default('worker')}} node taint to NoSchedule
  block:
    - name: Apply NoSchedule taint
      environment:
        KUBECONFIG: "./auth/kubeconfig"
      ansible.builtin.shell: |
        ./kubectl taint node {{workerid}} node-role.kubernetes.io/{{worker_type | default('worker')}}:NoSchedule --kubeconfig auth/kubeconfig &> /dev/null
        echo $(./oc get nodes -o custom-columns=NAME:.metadata.name)
      register: result
      until: result.stdout.find(workerid) != -1
      retries: 30
      delay: 10
  rescue:
    - name: Apply NoSchedule taint manually
      ansible.builtin.debug:
        msg: "Please update {{worker_type | default('worker')}} node label manually via: ./kubectl taint node {{workerid}} node-role.kubernetes.io/{{worker_type | default('worker')}}='':NoSchedule --kubeconfig auth/kubeconfig"