---
- name: 'Import common yaml'
  ansible.builtin.include_tasks: "{{ playbook_dir }}/common.yaml"

- name: 'Export infra ID'
  ansible.builtin.shell:
    cmd: "jq -r .infraID metadata.json"
  register: infra_id

- name: 'Update storage node label and taint'
  ansible.builtin.include_tasks: label.yaml
  vars:
    workerid: "{{ item.1 }}-{{ item.0 }}"
    worker_type: "storage"
  when: os_storage_nodes_number > 0 
  with_indexed_items: "{{ [os_storage_server_name] * os_storage_nodes_number }}"

- name: 'Update infra node label and taint'
  ansible.builtin.include_tasks: label.yaml
  vars:
    workerid: "{{ item.1 }}-{{ item.0 }}"
    worker_type: "infra"
  when: os_infra_nodes_number > 0 
  with_indexed_items: "{{ [os_infra_server_name] * os_infra_nodes_number }}"