# *+------------------------------------------------------------------------+
# *| © Copyright IBM Corp. 2026                                             |
# *| [04.02.2026]                                                           |
# *|   - Tested with ACC 1.2.13                                             |
# *|   - Initial release                                                    |
# *| [06.26.2026]                                                           |
# *|   - Tested with ACC 1.2.14                                             |
# *|   - Added execution timestamp and ACC about info display               |
# *+------------------------------------------------------------------------+

- name: ACC playbook, run by ACC-owner, to get task information
  hosts: localhost
  gather_facts: true
  vars_files:
    - owner_vars.yaml

  pre_tasks:
    - name: Reminder - Export appliance-owner credentials
      ansible.builtin.pause:
        prompt: |
          Before running this playbook, please export credentials:

          export ACC_OWNER_PASSWORD=<owner_password>

          Press Ctrl+C now to cancel if you haven't done this.
          The playbook will continue shortly.
        seconds: 5

    - name: Check required environment variables
      vars:
        required_env_vars:
          - ACC_OWNER_PASSWORD

      ansible.builtin.fail:
        msg: "Missing required environment variable: {{ item }}"
      when: lookup('env', item) == ""
      loop: "{{ required_env_vars }}"

  tasks:
    - name: 00 - Get authentication token from the ACC as appliance-owner
      tags: owner, install
      ansible.builtin.uri:
        url: "{{ acc_url }}/user/token"
        method: POST
        body:
          username: "{{ cc_owner_user }}"
          password: "{{ cc_owner_password }}"
        body_format: json
        return_content: true
        validate_certs: false
      register: auth_response

    - name: Extract the token
      tags: owner, install
      ansible.builtin.set_fact:
        access_token: "{{ auth_response.json.access_token }}"

    - name: Display execution info and ACC about information
      ansible.builtin.include_tasks:
        file: common_display_info.yaml

    - name: Enter the task ID
      ansible.builtin.pause:
        prompt: "Enter the task ID (integer):"
      register: task_id

    - name: Get task status from ACC
      ansible.builtin.uri:
        url: "{{ acc_url }}/tasks/{{ task_id.user_input | trim }}/status"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
        validate_certs: false
        return_content: true
      register: task_status_response

    - name: Display task status response
      ansible.builtin.debug:
        var: task_status_response.json
